export const MEGA_STRIPE_REF_PRESETS = {
  first_contact: [
    { key: 'NX-01', src: '/tmp/CALIBRTGE/first_contact/first-contact-nx-01-black-white.png' },
    { key: 'NCC-1701', src: '/tmp/CALIBRTGE/first_contact/first-contact-ncc-1701-black-white.png' },
    { key: 'NCC-1701-D', src: '/tmp/CALIBRTGE/first_contact/first-contact-ncc-1701-d-black-white.png' },
    { key: 'Wormhole', src: '/tmp/CALIBRTGE/first_contact/first-contact-wormhole-black-white.png' },
    { key: 'Plasma escape', src: '/tmp/CALIBRTGE/first_contact/first-contact-plasma-escape-black-white.png' },
    { key: "Vulcan's end", src: '/tmp/CALIBRTGE/first_contact/first-contact-vulcans-end-black-white.png' },
    { key: 'The Phoenix', src: '/tmp/CALIBRTGE/first_contact/first-contact-the-phoenix-black-white.png' },
  ],
  austen: [
    { key: 'P&P 1', src: '/tmp/CALIBRTGE/austen/crosswords/pride_and_prejudice/1.png' },
    { key: 'P&P 3', src: '/tmp/CALIBRTGE/austen/crosswords/pride_and_prejudice/3.png' },
    { key: 'P&P 5', src: '/tmp/CALIBRTGE/austen/crosswords/pride_and_prejudice/5.png' },
    { key: 'P&P 7', src: '/tmp/CALIBRTGE/austen/crosswords/pride_and_prejudice/7.png' },
    { key: 'Persuasion 1', src: '/tmp/CALIBRTGE/austen/crosswords/persuasion/1.jpg' },
    { key: 'Persuasion 3', src: '/tmp/CALIBRTGE/austen/crosswords/persuasion/3.jpg' },
    { key: 'Persuasion 5', src: '/tmp/CALIBRTGE/austen/crosswords/persuasion/5.jpg' },
    { key: 'Persuasion 7', src: '/tmp/CALIBRTGE/austen/crosswords/persuasion/7.jpg' },
    { key: 'S&S 1', src: '/tmp/CALIBRTGE/austen/crosswords/sense_and_sensibility/sense-and-sensibility-1.jpg' },
    { key: 'S&S 3', src: '/tmp/CALIBRTGE/austen/crosswords/sense_and_sensibility/sense-and-sensibility-3.jpg' },
    { key: 'S&S 5', src: '/tmp/CALIBRTGE/austen/crosswords/sense_and_sensibility/sense-and-sensibility-5.jpg' },
    { key: 'S&S 7', src: '/tmp/CALIBRTGE/austen/crosswords/sense_and_sensibility/sense-and-sensibility-7.jpg' },
    { key: 'Quote 1', src: '/tmp/CALIBRTGE/austen/quotes/1.jpg' },
    { key: 'Quote 2', src: '/tmp/CALIBRTGE/austen/quotes/2.jpg' },
    { key: 'Quote 3', src: '/tmp/CALIBRTGE/austen/quotes/3.jpg' },
    { key: 'Quote 4', src: '/tmp/CALIBRTGE/austen/quotes/4.jpg' },
    { key: 'Quote 5', src: '/tmp/CALIBRTGE/austen/quotes/5.jpg' },
    { key: 'Keep calm (black)', src: '/tmp/CALIBRTGE/austen/keep_calm/keep-calm-black.webp' },
    { key: 'Keep calm (red)', src: '/tmp/CALIBRTGE/austen/keep_calm/keep-calm-multi-red.webp' },
    { key: 'Darcy 16', src: '/tmp/CALIBRTGE/austen/looking_for_my_darcy/LOOKING FOR MY DARCY 16.jpeg' },
    { key: 'Darcy 17', src: '/tmp/CALIBRTGE/austen/looking_for_my_darcy/LOOKING FOR MY DARCY 17.jpeg' },
    { key: 'Darcy 18', src: '/tmp/CALIBRTGE/austen/looking_for_my_darcy/LOOKING FOR MY DARCY 18.jpeg' },
    { key: 'Darcy 19', src: '/tmp/CALIBRTGE/austen/looking_for_my_darcy/LOOKING FOR MY DARCY 19.jpeg' },
    { key: 'Pemberley', src: '/tmp/CALIBRTGE/austen/pemberley_house/permberley-black.jpg' },
  ],
  cube: [
    { key: 'Iron Kong', src: '/tmp/CALIBRTGE/cube/iron-kong.png' },
    { key: 'Iron Cube', src: '/tmp/CALIBRTGE/cube/iron-cube.png' },
    { key: 'RoboCube', src: '/tmp/CALIBRTGE/cube/robocube.png' },
    { key: 'Cylon Cube', src: '/tmp/CALIBRTGE/cube/cylon-cube.png' },
    { key: 'MaschinenCube', src: '/tmp/CALIBRTGE/cube/maschinenCube.png' },
    { key: 'Mazinger C', src: '/tmp/CALIBRTGE/cube/mazinger-c.png' },
    { key: 'Afrodita C', src: '/tmp/CALIBRTGE/cube/afrodita-c.png' },
    { key: '3cube-p0', src: '/tmp/CALIBRTGE/cube/3cube-p0.png' },
    { key: 'Cyber Cube', src: '/tmp/CALIBRTGE/cube/cyber-cube.png' },
    { key: 'Darth Cube', src: '/tmp/CALIBRTGE/cube/darth-cube.png' },
  ],
  miscellania: [
    { key: 'DJ Vader', src: '/tmp/CALIBRTGE/miscellania/miscellania-dj-vader-black-white.png' },
    { key: 'Deathstar2D2', src: '/tmp/CALIBRTGE/miscellania/miscellania-dead-star2d2-black-white.png' },
  ],
  the_human_inside: [
    { key: 'Terminator', src: '/tmp/CALIBRTGE/the_human_inside/terminator.png' },
    { key: 'Robocop', src: '/tmp/CALIBRTGE/the_human_inside/robocop.png' },
    { key: 'Robby the robot', src: '/tmp/CALIBRTGE/the_human_inside/robby-the-robot.png' },
    { key: 'C3P0', src: '/tmp/CALIBRTGE/the_human_inside/c3p0.png' },
    { key: 'Darth Vader', src: '/tmp/CALIBRTGE/the_human_inside/darth-vader.png' },
    { key: 'Cylon 03', src: '/tmp/CALIBRTGE/the_human_inside/cylon-03.png' },
    { key: 'Cylon 78', src: '/tmp/CALIBRTGE/the_human_inside/cylon-78.png' },
    { key: 'Cyber-man', src: '/tmp/CALIBRTGE/the_human_inside/cyber-man.png' },
    { key: 'Maschinenmensch', src: '/tmp/CALIBRTGE/the_human_inside/maschinenmensch.png' },
    { key: 'Mazinger Z', src: '/tmp/CALIBRTGE/the_human_inside/mazinger-z.png' },
    { key: 'Afrodita A', src: '/tmp/CALIBRTGE/the_human_inside/afrodita-a.png' },
    { key: 'Iron Man 08', src: '/tmp/CALIBRTGE/the_human_inside/iron-man-08.png' },
    { key: 'Iron Man 68', src: '/tmp/CALIBRTGE/the_human_inside/iron-man-68.png' },
  ],
};

MEGA_STRIPE_REF_PRESETS.thin = MEGA_STRIPE_REF_PRESETS.the_human_inside;
