import { chromium } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1920, height: 946 }, deviceScaleFactor: 1 });
const p = await ctx.newPage();
const errors = [];
p.on('response', (r) => { if (r.status() >= 400) errors.push(`HTTP ${r.status()} ${r.url().slice(0, 80)}`); });
await p.goto('http://127.0.0.1:3003/nova/inici', { waitUntil: 'load', timeout: 45000 });
await p.waitForTimeout(2500);
await p.click('button:has(svg.lucide-search)', { timeout: 8000 }).catch(() => {});
await p.waitForTimeout(4500);
const peca = await p.evaluateHandle(() => {
  const v = document.querySelector('[data-mega-page-viewport="2"]');
  const tira = v.querySelector('[data-carrusel="1"] > div').firstElementChild;
  return [...tira.querySelectorAll('button')][0];
});
console.log('icona', await peca.asElement().getAttribute('title'));
await peca.asElement().click();
await p.waitForTimeout(3000);
console.log('url', (await p.evaluate(() => location.href)).slice(0, 90));
console.log('pdp?', await p.evaluate(() => /pdp|producte|product/i.test(location.pathname)));
console.log('errors', JSON.stringify(errors.slice(0, 3)));
await b.close();
