import { chromium } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1920, height: 946 }, deviceScaleFactor: 1 });
const p = await ctx.newPage();
p.on('console', (m) => { if (m.type() === 'error') console.log('ERR', m.text().slice(0, 120)); });
await p.goto('http://127.0.0.1:3003/nova/inici?active=first_contact', { waitUntil: 'load', timeout: 180000 });
await p.waitForTimeout(4000);
await p.click('button:has(svg.lucide-search)').catch(() => {});
await p.waitForSelector('[data-mega-page-viewport="2"]', { timeout: 30000 });
await p.waitForTimeout(9000);
const triat = () => p.evaluate(() => {
  const cg = document.querySelector('[data-p2-color-grid]');
  const m = [...cg.querySelectorAll('button')].find((x) => getComputedStyle(x).outlineStyle === 'solid');
  return m ? m.getAttribute('data-color-barra') : null;
});
const c = await p.evaluate(() => { const r = document.querySelector('[data-p2-color-grid]').getBoundingClientRect(); return { x: Math.round(r.left + r.width / 2), y: Math.round(r.top + r.height / 2) }; });
console.log('abans', await triat(), 'punt', JSON.stringify(c));
await p.mouse.move(c.x, c.y);
await p.mouse.wheel(0, -120);
await p.waitForTimeout(800);
console.log('despres de rodeta AMUNT (deltaY -120)', await triat());
await p.mouse.wheel(0, 120);
await p.waitForTimeout(800);
console.log('despres de rodeta AVALL', await triat());
await ctx.close();
await b.close();
