import { chromium } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 768, height: 1024 }, hasTouch: true, deviceScaleFactor: 1 });
const p = await ctx.newPage();
await p.goto('http://127.0.0.1:3007/?active=first_contact', { waitUntil: 'load' });
await p.waitForTimeout(2500);
await p.click('button:has(svg.lucide-search)').catch(()=>{});
await p.waitForTimeout(4500);
const r = await p.evaluate(() => {
  const e = document.querySelector('[data-vertical-megaslide="2"]');
  const f = e.querySelector('[data-vertical-franja="1"]');
  const c = f.firstElementChild;
  const bf = f.getBoundingClientRect(), bc = c.getBoundingClientRect();
  const b0 = e.getBoundingClientRect();
  const col = e.querySelector('[data-vertical-colleccions="1"]').getBoundingClientRect();
  return { franja: [Math.round(bf.width), Math.round(bf.height)], casella: [Math.round(bc.width), Math.round(bc.height)], colleccions: Math.round(col.height), comp: [Math.round(b0.width), Math.round(b0.height)] };
});
console.log(JSON.stringify(r));
const el = await p.$('[data-vertical-megaslide="2"]');
await el.screenshot({ path: '/tmp/p2-fill.png' });
await b.close();
